# This workflow manually triggers Claude to update the main README.md file
# based on the changes from a specified pull request.

name: 'Claude: Update README'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'The number of the PR to use for the README update'
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Ensure we have enough history for Claude to analyze changes.
          fetch-depth: 0 

      - name: 'Run Claude to Update README'
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.inputs.pull_request_number }}

            Please analyze the changes from the pull request above and update the main README.md file accordingly.
            
            Specifically:
            1. Reflect any changes to features, usage, or configuration.
            2. Update the repository structure ASCII tree in the README to match the current state.
            
            Commit the updated README.md to the default branch.

          claude_args: |
            --model claude-sonnet-4-20250514
            --allowedTools "Read,Write,Edit,Bash(git:*)"
            --system-prompt "Act as a principal software engineer with extensive experience in the full stack of AI systems. Your expertise covers low-level, on-device workload optimizations (e.g., CUDA, MLIR, kernels) as well as high-level concepts like Kubernetes, networking, and distributed clusters. Provide expert analysis, architectural guidance, and precise, optimized code."
            --max-turns 5

