# This GitHub Actions workflow provides both automatic and interactive code assistance
# using Anthropic's Claude model, based on the latest best practices.

name: 'Claude Assistant'

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened, assigned]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  claude-assistant:
    runs-on: ubuntu-latest
    if: github.event.sender.type != 'Bot'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch only the latest commit for efficiency, as recommended.
          fetch-depth: 1

      - name: Set Automation Prompt and Tools
        id: set_context
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PROMPT_TEXT=REPO: ${{ github.repository }}\nPR NUMBER: ${{ github.event.pull_request.number }}\n\nAs a principal engineer, please provide a thorough review of this pull request. Use inline comments for specific code suggestions and a top-level comment for the overall summary." >> $GITHUB_OUTPUT
            echo "ALLOWED_TOOLS=mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*)" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "issues" ]]; then
            echo "PROMPT_TEXT=REPO: ${{ github.repository }}\nISSUE NUMBER: ${{ github.event.issue.number }}\n\nPlease analyze this issue, propose a solution, and implement the fix. Create a new branch and open a pull request with the changes." >> $GITHUB_OUTPUT
            echo "ALLOWED_TOOLS=Read,Write,Edit,Bash(git:*)" >> $GITHUB_OUTPUT
          else
            echo "PROMPT_TEXT=" >> $GITHUB_OUTPUT
            echo "ALLOWED_TOOLS=Read,Write,Edit,Bash(git:*),mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*)" >> $GITHUB_OUTPUT
          fi

      - name: 'Run Claude Assistant Action'
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: ${{ steps.set_context.outputs.PROMPT_TEXT }}
          trigger_phrase: '@claude'
          assignee_trigger: 'claude-bot'
          claude_args: |
            --model claude-sonnet-4-20250514
            --allowedTools "${{ steps.set_context.outputs.ALLOWED_TOOLS }}"
            --system-prompt "Act as a principal software engineer with extensive experience in the full stack of AI systems. Your expertise covers low-level, on-device workload optimizations (e.g., CUDA, MLIR, kernels) as well as high-level concepts like Kubernetes, networking, and distributed clusters. Provide expert analysis, architectural guidance, and precise, optimized code."
            --max-turns 20

